routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\authController;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\depanController;
use App\Http\Controllers\skillController;
use App\Http\Controllers\halamanController;
use App\Http\Controllers\profileController;
use App\Http\Controllers\educationController;
use App\Http\Controllers\experienceController;
use App\Http\Controllers\pengaturanHalamanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', [depanController::class,"index"]);

Route::redirect('home', 'dashboard');

Route::get('/auth',[authController::class,"index"])->name('login');
Route::get('/auth/redirect', [ authController::class, "redirect" ])->middleware('guest');
Route::get('/auth/callback',  [ authController::class, "callback" ])->middleware('guest');
Route::get('/auth/logout',[authController::class,"logout"]);



Route::prefix('dashboard')->middleware('auth')->group(
    function (){
    Route::get('/',[halamanController::class,'index']);
    Route::resource('halaman', halamanController::class);
    Route::resource('experience', experienceController::class);
    Route::resource('education', educationController::class);
    Route::get('skill', [skillController::class,"index"])->name('skill.index');
    Route::post('skill', [skillController::class,"update"])->name('skill.update');
    Route::get('profile', [profileController::class,"index"])->name('profile.index');
    Route::post('profile', [profileController::class,"update"])->name('profile.update');
    Route::get('pengaturanhalaman', [pengaturanHalamanController::class,"index"])->name('pengaturanhalaman.index');
    Route::post('pengaturanhalaman', [pengaturanHalamanController::class,"update"])->name('pengaturanhalaman.update');

    }
);

app/Http/Controllers/experienceController.php
<?php

namespace App\Http\Controllers;

use App\Models\riwayat;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class experienceController extends Controller
{
    function __construct()
    {
        $this->_tipe='experience';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data =riwayat::where('tipe',$this->_tipe)->orderBy('tgl_akhir','desc')->get();
        return view('dashboard.experience.index')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.experience.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Session::flash('judul',$request->judul);
        Session::flash('info1',$request->info1);
        Session::flash('tgl_mulai',$request->tgl_mulai);
        Session::flash('tgl_akhir',$request->tgl_akhir);
        Session::flash('isi',$request->isi);

        $request->validate(
            [
                'judul' => 'required',
                'info1' => 'required',
                'tgl_masuk' => 'required',
                'isi' => 'required',
            ],[
                'judul.required'=>'Judul wajib diisi',
                'info1.required'=>'Nama perusahaan wajib diisi',
                'tgl_mulai.required'=>'Tanggal mulai wajib diisi',
                'isi.required'=>'Isian tulisan wajib diisi',
            ]
            );

            $data =[
                'judul' => $request->judul,
                'info1' =>$request->info1,
                'tipe' =>$this->_tipe,
                'tgl_masuk' =>$request->tgl_masuk,
                'tgl_akhir' =>$request->tgl_akhir,
                'isi' =>$request->isi
            ];
            riwayat::create($data);

            return redirect()->route('experience.index')->with('success','berhasil menambahkan data pengalaman');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = riwayat::where('id',$id)->where('tipe', $this->_tipe)->first();
        return view('dashboard.experience.edit')->with('data', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        riwayat::where('id',$id)->where('tipe',$this->_tipe)->delete();
        return redirect()->route('experience.index')->with('success','Berhasil menghapus data');
    }
}

resources/views/dashboard/experience/create.blade.php
@extends('dashboard.layout')

@section('konten')
    <div class="pb-3"><a href="{{route('experience.index')}}" class="btn btn-secondary">
        << Kembali</a>
    </div>
    <form action="{{route('experience.store')}}" method="POST">
        @csrf
    <div class="mb-3">
      <label for="judul" class="form-label">Posisi</label>
      <input type="text"
        class="form-control form-control-sm" name="judul" id="judul" aria-describedby="helpId" placeholder="Posisi"
        value="{{ Session::get('judul') }}">
    </div>

    <div class="mb-3">
      <label for="info1" class="form-label">Nama Perusahaan</label>
      <input type="text"
        class="form-control form-control-sm" name="info1" id="info1" aria-describedby="helpId" placeholder="Perusahaan"
        value="{{ Session::get('info1') }}">
    </div>

    <div class="mb-3">
      <div class="row">
        <div class="col-auto">Tanggal Mulai</div>
        <div class="col-auto"><input type="date" class="form-control form-control-sm" name="tgl_mulai" placeholder="dd/mm/yy" value="{{ Session::get('tgl_mulai') }}"></div>
        <div class="col-auto">Tanggal Akhir</div>
        <div class="col-auto"><input type="date" class="form-control form-control-sm" name="tgl_akhir" placeholder="dd/mm/yy" value="{{ Session::get('tgl_akhir') }}"></div>
      </div>
    </div>


    <div class="mb-3">
        <label for="isi" class="form-label">Isi</label>
        <textarea class="form-control summernote" name="isi" rows="5">{{ Session::get('isi') }}</textarea>
      </div>
      <button class="btn btn-primary" name="simpan" type="submit">SIMPAN</button>
    </form>
@endsection

resources/views/dashboard/experience/edit.blade.php
@extends('dashboard.layout')

@section('konten')
    <div class="pb-3"><a href="{{route('experience.index')}}" class="btn btn-secondary">
        << Kembali</a>
    </div>
    <form action="{{route('experience.update', $data->id)}}" method="POST">
        @csrf
        @method('PUT')
    <div class="mb-3">
      <label for="judul" class="form-label">Posisi</label>
      <input type="text"
        class="form-control form-control-sm" name="judul" id="judul" aria-describedby="helpId" placeholder="Posisi"
        value="{{ $data->judul }}">
    </div>
    <div class="mb-3">
        <label for="info1" class="form-label">Nama Perusahaan</label>
        <textarea class="form-control summernote" name="isi" rows="5">{{ $data->info1 }}</textarea>
      </div>

      <div class="mb-3">
        <div class="row">
          <div class="col-auto">Tanggal Mulai</div>
          <div class="col-auto"><input type="date" class="form-control form-control-sm" name="tgl_mulai" placeholder="dd/mm/yy" value="{{ $data->tgl_mulai }}"></div>
          <div class="col-auto">Tanggal Akhir</div>
          <div class="col-auto"><input type="date" class="form-control form-control-sm" name="tgl_akhir" placeholder="dd/mm/yy" value="{{ $data->tgl_akhir }}"></div>
        </div>
      </div>

      <div class="mb-3">
        <label for="isi" class="form-label">Isi</label>
        <textarea class="form-control summernote" name="isi" rows="5">{{ Session::get('isi') }}</textarea>
      </div>

      <button class="btn btn-primary" name="simpan" type="submit">SIMPAN</button>
    </form>
@endsection

resources/views/dashboard/experience/index.blade.php
@extends('dashboard.layout')

@section('konten')
<p class="card-title">Pengalaman</p>
<div class="pb-3"><a href="{{ route('experience.create') }}" class="btn btn-primary">+Tambah Pengalaman</a></div>
<div class="table-responsive">
<table class="table table-stripped">
    <thead>
        <tr>
            <th class="col-1">No.</th>
            <th>Posisi</th>
            <th>Nama Perusahaan</th>
            <th>Tanggal Mulai</th>
            <th>Tanggal Akhir</th>
            <th class="col-2">Aksi</th>
        </tr>
    </thead>
    <tbody>
        <?php $i=1; ?>
        @foreach ( $data as $item)
        <tr>
            <td>{{$i}}</td>
            <td>{{ $item->judul }}</td>
            <td>{{ $item->info1 }}</td>
            <td>{{ $item->tgl_mulai_indo }}</td>
            <td>{{ $item->tgl_akhir_indo }}</td>
            <td>
                <a href="{{ route('experience.edit', $item->id) }}" class="btn btn-sm btn-warning">Edit</a>
                <form onsubmit="return confirm('Yakin ingin menghapus data ini?')" action="{{ route('experience.destroy', $item->id)}}" class="d-inline" method="POST">
                    @csrf
                    @method('DELETE')
                <button class="btn btn-sm btn-danger" type="submit" name="submit">Hapus</button>
                </form>
            </td>
        </tr>
        <?php $i++; ?>
        @endforeach
        
    </tbody>
</table>
</div>
    
@endsection