routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\authController;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\depanController;
use App\Http\Controllers\skillController;
use App\Http\Controllers\halamanController;
use App\Http\Controllers\profileController;
use App\Http\Controllers\educationController;
use App\Http\Controllers\experienceController;
use App\Http\Controllers\pengaturanHalamanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', [depanController::class,"index"]);

Route::redirect('home', 'dashboard');

Route::get('/auth',[authController::class,"index"])->name('login');
Route::get('/auth/redirect', [ authController::class, "redirect" ])->middleware('guest');
Route::get('/auth/callback',  [ authController::class, "callback" ])->middleware('guest');
Route::get('/auth/logout',[authController::class,"logout"]);



Route::prefix('dashboard')->middleware('auth')->group(
    function (){
    Route::get('/',[halamanController::class,'index']);
    Route::resource('halaman', halamanController::class);
    Route::resource('experience', experienceController::class);
    Route::resource('education', educationController::class);
    Route::get('skill', [skillController::class,"index"])->name('skill.index');
    Route::post('skill', [skillController::class,"update"])->name('skill.update');
    Route::get('profile', [profileController::class,"index"])->name('profile.index');
    Route::post('profile', [profileController::class,"update"])->name('profile.update');
    Route::get('pengaturanhalaman', [pengaturanHalamanController::class,"index"])->name('pengaturanhalaman.index');
    Route::post('pengaturanhalaman', [pengaturanHalamanController::class,"update"])->name('pengaturanhalaman.update');

    }
);

app/Models/halaman.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class halaman extends Model
{
    use HasFactory;
    protected $table ="halaman";
    protected $fillable =['judul','isi'];
}

app/Http/Controllers/halamanController.php
<?php

namespace App\Http\Controllers;

use App\Models\halaman;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class halamanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $data =halaman::orderBy('judul','asc')->get();
        return view('dashboard.halaman.index')->with('data',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.halaman.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Session::flash('judul',$request->judul);
        Session::flash('judul',$request->isi);

        $request->validate(
            [
                'judul' => 'required',
                'isi' => 'required',
            ],[
                'judul.required'=>'Judul wajib diisi',
                'isi.required'=>'Isian tulisan wajib diisi',
            ]
            );

            $data =[
                'judul' => $request->judul,
                'isi' =>$request->isi
            ];
            halaman::create($data);

            return redirect()->route('halaman.index')->with('success','berhasil menambahkan data');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = halaman::where('id',$id)->first();
        return view('dashboard.halaman.edit')->with('data', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            [
                'judul' => 'required',
                'isi' => 'required',
            ],[
                'judul.required'=>'Judul wajib diisi',
                'isi.required'=>'Isian tulisan wajib diisi',
            ]
            );

            $data =[
                'judul' => $request->judul,
                'isi' =>$request->isi
            ];
            halaman::where('id',$id)->update($data);

            return redirect()->route('halaman.index')->with('success','berhasil update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        halaman:where('id',$id)->delete();
        return redirect()->route('halaman.index')->with('success','Berhasil menghapus data');
    }
}

resources/views/dashboard/halaman/create.blade.php
@extends('dashboard.layout')

@section('konten')
    <div class="pb-3"><a href="{{route('halaman.index')}}" class="btn btn-secondary">
        << Kembali</a>
    </div>
    <form action="{{route('halaman.store')}}" method="POST">
        @csrf
    <div class="mb-3">
      <label for="judul" class="form-label">Judul</label>
      <input type="text"
        class="form-control form-control-sm" name="judul" id="judul" aria-describedby="helpId" placeholder="Judul"
        value="{{ Session::get('judul') }}">
      
    </div>
    <div class="mb-3">
        <label for="isi" class="form-label">Isi</label>
        <textarea class="form-control summernote" name="isi" rows="5">{{ Session::get('isi') }}</textarea>
      </div>
      <button class="btn btn-primary" name="simpan" type="submit">SIMPAN</button>
    </form>
@endsection

resources/views/dashboard/halaman/edit.blade.php
@extends('dashboard.layout')

@section('konten')
    <div class="pb-3"><a href="{{route('halaman.index')}}" class="btn btn-secondary">
        << Kembali</a>
    </div>
    <form action="{{route('halaman.update', $data->id)}}" method="POST">
        @csrf
        @method('PUT')
    <div class="mb-3">
      <label for="judul" class="form-label">Judul</label>
      <input type="text"
        class="form-control form-control-sm" name="judul" id="judul" aria-describedby="helpId" placeholder="Judul"
        value="{{ $data->judul }}">
      
    </div>
    <div class="mb-3">
        <label for="isi" class="form-label">Isi</label>
        <textarea class="form-control summernote" name="isi" rows="5">{{ $data->isi }}</textarea>
      </div>
      <button class="btn btn-primary" name="simpan" type="submit">SIMPAN</button>
    </form>
@endsection

resources/views/dashboard/halaman/index.blade.php
@extends('dashboard.layout')

@section('konten')
<p class="card-title">Halaman</p>
<div class="pb-3"><a href="{{ route('halaman.create') }}" class="btn btn-primary">+Tambah Halaman</a></div>
<div class="table-responsive">
<table class="table table-stripped">
    <thead>
        <tr>
            <th class="col-1">No.</th>
            <th>Judul</th>
            <th class="col-2">Aksi</th>
        </tr>
    </thead>
    <tbody>
        <?php $i=1; ?>
        @foreach ( $data as $item)
        <tr>
            <td>{{$i}}</td>
            <td>{{ $item->judul }}</td>
            <td>
                <a href="{{ route('halaman.edit', $item->id) }}" class="btn btn-sm btn-warning">Edit</a>
                <form onsubmit="return confirm('Yakin ingin menghapus data ini?')" action="{{ route('halaman.destroy', $item->id)}}" class="d-inline" method="POST">
                    @csrf
                    @method('DELETE')
                <button class="btn btn-sm btn-danger" type="submit" name="submit">Hapus</button>
                </form>
            </td>
        </tr>
        <?php $i++; ?>
        @endforeach
        
    </tbody>
</table>
</div>
    
@endsection